### ISSUE TITLE
Background style "blur" doesn't show up

### ISSUE THREAD

**Issue by ndl010** [jurialmunkey/skin.arctic.horizon#336]
Dear jurialmunkey,

I'm really thanks for making such a wonderful kodi skin. I really appreaciat it.

Anyway, I'm using this arctic horizon skin with korean language, and latest version of tmdb helper causes ascii problem like any other special characters.

> Error code

> 2021-01-26 18:16:44.246 T:140434684765952  NOTICE: [plugin.video.themoviedb.helper]

> ERROR WITH TRACEBACK!

> 'exceptions.UnicodeDecodeError' object has no attribute '__traceback__'

> ['lib.monitor.common set_property', '\n', u'Error Type: UnicodeDecodeError\nError Contents: (\'ascii\', "2021\'\\xeb\\x85\\x84\' M\'\\xec\\x9b\\x94\' 13\'\\xec\\x9d\\xbc\' Wednesday", 5, 6, \'ordinal not in range(128)\')', 

So I tried kodi repository version of tmdb helper(2.4.36 version). It works just fine except background wallpaper.

When I'm using kodi repository version of tmdb helper, background image doesn't show. Just black image.

Other background style like overlay, vignette works fine. Only blurred background doesn't show up.

Then, I updated tmdb helper to latest version and wallpaper show up normally.

Would you please help me solve this problem?

I really like blurred version of default background.

**Comment by drinfernoo** [comment]
So it works in the version from jurialmunkey's repo? 🤔 That would make sense, as it's the maintained version. The version in Kodi's repo hasn't been updated in about 9 months.

**Comment by ndl010** [comment]
Yes it works fine with jurialmunkey's version.

My question is, the function of tmdb helper is related to background style??

I'm not sure if it's a bug or intended function.

**Comment by jurialmunkey** [comment]
Yes you need latest version of TMDbhelper for blur. I'll look into the encoding error.

**Comment by ndl010** [comment]
# 

> `@```

**Comment by ndl010** [comment]
Oops sorry, I tried to upload my kodi log.
Here's my another error log.

> Error code
2021-01-26 22:53:58.546 T:140583862818560   ERROR: /storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/addon/window.py:32: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
                                              if value and get_property(name) == value:
2021-01-26 22:54:08.552 T:140583862818560   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xea in position 269: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.themoviedb.helper/script.py", line 7, in <module>
                                                Script().router()
                                              File "/storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/script/router.py", line 358, in router
                                                return self.routing_table[route_taken](**self.params)
                                              File "/storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/script/router.py", line 337, in <lambda>
                                                'add_path': lambda **kwargs: WindowManager(**kwargs).router(),
                                              File "/storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/window/manager.py", line 245, in router
                                                return self.add_path(self.params['add_path'])
                                              File "/storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/window/manager.py", line 213, in add_path
                                                self.call_auto()
                                              File "/storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/window/manager.py", line 202, in call_auto
                                                return self.event_loop()
                                              File "/storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/window/manager.py", line 133, in event_loop
                                                self._on_add()
                                              File "/storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/window/manager.py", line 63, in _on_add
                                                self.set_properties(self.position, window.get_property(PREFIX_ADDPATH))
                                              File "/storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/window/manager.py", line 188, in set_properties
                                                window.get_property(PREFIX_CURRENT, set_property=path)
                                              File "/storage/.kodi/addons/plugin.video.themoviedb.helper/resources/lib/addon/window.py", line 20, in get_property
                                                window.setProperty(name, u'{}'.format(set_property))
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xea in position 269: ordinal not in range(128)
                                            -->End of Python script error report<--

**Comment by jurialmunkey** [comment]
@ndl010 - Are you still having this error? I think I might've fixed it already in TMDbH in response to a separate issue.

**Comment by ndl010** [comment]
Thanks for your support! It works fine with me!

I'll close this issue. Really thank you.
